backend/fixtures/questions.json
backend/models.py

Added contents for all care service questions originally created by @lennart-huesing with updated format proposed by @DasProffi.

feat: Added questions with new data model format

---

backend/src/handle_calculations.py
backend/src/handle_questions.py
backend/urls.py
start.sh

Closes #24 
Closes #17 
Get: http://localhost:8000/api/questions/1/ : Returns the questions including a 'selected' attribute (True if this option has been previously selected)
Post: http://localhost:8000/api/questions/1/: Enter an entry for the patient:
The body needs to contain these:
return ('is_in_isolation' not in body
or 'data_accepted' not in body
or 'station' not in body
or 'room_name' not in body
or 'bed_number' not in body
or 'barthel_index' not in body
or 'expanded_barthel_index' not in body
or 'mini_mental_status' not in body
or 'selected_care_services' not in body)
The format of the selected_care_services should equal the result returned by the corresponding get request of the same route.
Post: http://localhost:8000/api/calculate/: Calculates the minutes calculated for a …

Endpoints for the frontend

---

frontend/templates/frontend/station_patient_list.html
frontend/views.py

15 view stations patient view

---

backend/src/handle_patients.py
backend/urls.py

Please note: This branch relies on the model DailyClassifications which will be changed by https://github.com/CombiRWTH/medical-staff-assessment/pull/55/files. Which ever gets merged last, needs to adjust this.
Closes #32 
For Testing this endpoint you need at least one Station, one Patient and a DailyClassification for them.
Patients are only assigned to a station if the classification has been made today or yesterday.
Example Response:
[
{
"id": 1,
"first_name": "Test Patient",
"last_name": "test",
"date_of_birth": "2024-11-20",
"weight": 1,
"height": 1,
"classified_today": false
},
{
"id": 2,
"first_name": "test2",
"last_name": "test",
"date_of_birth": "2024-11-20",
"weight": 1,
"height": 1,
"classified_today": true
}
]

Add the endpoint to retrieve the patients

---

backend/backend/src/handle_patients.py

Following format for the endpoint
GET /stations/id
```json
[
{
"id": 1,
"lastClassification": "2024-11-28",
"currentBed": "20",
"name": "Benedikt Ricken"
}
]
```

Adapt Patients list endpoint

---

backend/backend/admin.py
backend/backend/models.py
backend/backend/src/handle_questions.py

65 visit type

---

backend/backend/src/handle_patients.py

Closes #116 
I am only able to reproduce the bug related to the subquery.
Lmk if the other mentioned bug persists @DasProffi .

Adjust subquery of handle_patients for the bed number

---

frontend/pages/stations/[id]/[patientId]/[date]/index.tsx
frontend/src/api/classification.ts
frontend/src/data-models/classification.ts
frontend/src/util/formatDate.ts
frontend/src/util/parseDateString.ts

update result categories and minutes

---

frontend/pages/stations/[id]/[patientId]/[date]/index.tsx
frontend/src/api/classification.ts
frontend/src/util/formatDate.ts
frontend/src/util/parseDateString.ts

fix date and update logic

---

backend/backend/src/handle_stations.py
backend/backend/urls.py

add endpoint for analysis

---

backend/backend/src/handle_questions.py

Add sorting by id

---

frontend/Dockerfile

Update Frontend Dockerfile

---

frontend/pages/analysis/index.tsx
frontend/src/api/analysis.ts
frontend/src/util/export.ts

before updated endpoints

---

backend/backend/src/handle_patients.py

I extended the returned patient list with:
- aIndexPrevious
- sIndexPrevious
- aIndexToday
- sIndexToday
- todaysMinutes
Closes #149

Add todays and previous classification to the patients list

---

frontend/src/components/ClassificationCard.tsx

Icon is used now. A small problem arises when the text contains multiple short words. 
Discuss if we are okay with that or an alternative should be found

change tooltip

---

backend/backend/fixtures/patient_transfers.json
backend/backend/src/handle_questions.py

It is now possible to adjust the isolation status of a patient. Use 'questions/<int:station_id>/<int:patient_id>/<str:date>/' to put a body:
`{
''is_in_isolation": true/false
}`

183 allow for changing isolation status of a patient

---

backend/backend/models.py
backend/backend/src/handle_data_imports.py
backend/backend/urls.py
backend/cronjobs/src/nightshift_cronjob.py

You can either import Daily or Monthly data.
The files are more or less taken from the last data provided by svenja:
[CaregiverShiftDaily.xlsx](https://github.com/user-attachments/files/18299621/CaregiverShiftDaily.xlsx)
[CaregiverShiftMonthly.xlsx](https://github.com/user-attachments/files/18299622/CaregiverShiftMonthly.xlsx)

Add route to import shift plans

---

LICENSE

feat(License): Add license

---

backend/backend/src/handle_patients.py

Added the current room of a patient to the patient list. Bed number was already there.

Added current room to patientlist

---

frontend/.eslintrc.json
frontend/pages/stations/[id]/index.tsx
frontend/src/api/patients.ts
frontend/src/components/LastClassifiedBadge.tsx
frontend/src/data-models/patient.ts

add bed and room to patient list

---

frontend/pages/stations/[id]/[patientId]/[date]/index.tsx
frontend/src/api/classification.ts

add isolation checkbox

---

backend/backend/src/handle_stations.py

... instead of the sum of all missing classifications from last 7 days.
closes #223

Station overview now only shows todays missing classifications

---

backend/backend/src/handle_patients.py
frontend/pages/stations/[id]/[patientId]/[date]/index.tsx
frontend/src/api/dates.ts

Add missing classification boolean

---

frontend/pages/stations/index.tsx

Changed wordings for stationlist overview

---

backend/backend/src/handle_calculations.py
backend/cronjobs/crontab
backend/cronjobs/src/daily_calculation_cronjob.py
backend/cronjobs/src/monthly_calc_cronjob.py

The daily station workload is now computed via a cronjob.
Additionally it is also computed once all classifications have been made.
Same goes for the monthly station workload.
Also in case the data changes later on the daily/monthly data for that specific station and date is recomputated (i.e. classification is made on the next day) .

211 calculate sums of minutes at appropiate timings

---

backend/backend/src/handle_patients.py

update the endpoint return

---

backend/backend/src/handle_stations.py

Added an elif branch that calculates the workload over the last quarter

Added quarterly analysis

---

frontend/pages/stations/[id]/[patientId]/[date]/index.tsx
frontend/pages/stations/[id]/index.tsx
frontend/src/components/DatePicker/DatePickerButton.tsx
frontend/src/components/Select.tsx

Fixed bugs:
- patientlist minutesum calculation
- patientlist set classification hit boxes
- classification next patient button
- classification save button

fix: fix various bugs
